"""
Tests for the DPoP (RFC 9449) validation applied to the DPoP-protected endpoints.

The DPoP proofs and nonces here are the real thing, generated with the same `authutils`
functions the clients use. Only the lookup of the access token's signing key is mocked, so
that the tests do not need a live token issuer.
"""

import time
from unittest.mock import AsyncMock, patch

from authutils.dpop import generate_dpop_proof
from authutils.token.dpop_nonce import generate_stateless_nonce
from joserfc import jwk, jwt
import pytest

from gen3workflow.config import config, get_dpop_allowed_issuers
from gen3workflow.routes import ga4gh_tes, s3
from tests.conftest import (
    mock_arborist_request,
    mock_tes_server_request,
    MOCKED_S3_RESPONSE_XML,
    TEST_USER_ID,
)

TES_PATH = "/ga4gh/tes/v1/tasks"
S3_BUCKET = f"gen3wf-{config['HOSTNAME']}-{TEST_USER_ID}"
S3_PATH = f"/s3/{S3_BUCKET}"


@pytest.fixture(scope="module")
def token_signing_key():
    """
    The key the token issuer signs access tokens with.
    """
    return jwk.generate_key("RSA", 2048, private=True)


@pytest.fixture(scope="module")
def dpop_key():
    """
    The key a client proves possession of, equivalent to the one generated by the Gen3 SDK.
    """
    return jwk.generate_key("EC", "P-256", private=True)


@pytest.fixture(autouse=True)
def no_eks_cluster():
    """
    Keep task creation away from AWS: these tests are only about the DPoP flow.
    """
    original_val = config["EKS_CLUSTER_NAME"]
    config["EKS_CLUSTER_NAME"] = ""
    yield
    config["EKS_CLUSTER_NAME"] = original_val


@pytest.fixture(autouse=True)
def mock_token_signing_key_lookup(token_signing_key):
    """
    Return the test signing key instead of fetching the issuer's public keys.
    """
    with patch(
        "authutils.dpop.get_any_public_key_for_token_async",
        new_callable=AsyncMock,
        return_value=token_signing_key.as_pem(private=False),
    ) as mocked_lookup:
        yield mocked_lookup


def create_access_token(token_signing_key, dpop_key=None, **claim_overrides):
    """
    Create an access token as the auth service (e.g. Fence) would issue it.

    Args:
        token_signing_key (jwk.Key): the issuer's signing key
        dpop_key (jwk.Key | None): if provided, the token is bound to this key
        **claim_overrides: claims to add to or replace in the token

    Returns:
        str: the encoded access token
    """
    now = int(time.time())
    claims = {
        "sub": TEST_USER_ID,
        "iss": get_dpop_allowed_issuers()[0],
        "aud": config["VALID_AUTHZ_AUDIENCE"][0],
        "iat": now,
        "exp": now + 300,
        "pur": "access",
        "scope": ["openid", "user"],
    }
    if dpop_key:
        claims["cnf"] = {"jkt": dpop_key.thumbprint()}
    claims.update(claim_overrides)
    return jwt.encode({"alg": "RS256", "typ": "JWT"}, claims, token_signing_key)


def create_proof(
    dpop_key, method, path, access_token, external_prefix="", signed_overrides=None
):
    """
    Create a DPoP proof for a request, as the client's DPoP proxy would.

    Args:
        dpop_key (jwk.Key): the key to sign the proof with
        method (str): HTTP method of the request the proof is for
        path (str): path of the request, as this service sees it
        access_token (str): the access token the proof is presented with
        external_prefix (str): path prefix the reverse proxy would have stripped
        signed_overrides (dict | None): `method`, `url`, `access_token` or `nonce` values to
            sign instead of the ones matching the request

    Returns:
        str: the encoded DPoP proof
    """
    signed = {
        "method": method,
        "url": f"{config['DPOP_EXTERNAL_BASE_URL']}{external_prefix}{path}",
        "access_token": access_token,
        "nonce": generate_stateless_nonce(secret=config["DPOP_SHARED_SECRET"]),
    }
    signed.update(signed_overrides or {})
    return generate_dpop_proof(key=dpop_key, **signed)


def aws_auth_header(access_token):
    """
    Build the Authorization header an AWS client produces, with the token as the key ID.

    Args:
        access_token (str): the access token

    Returns:
        str: an AWS Signature Version 4 Authorization header value
    """
    return (
        f"AWS4-HMAC-SHA256 Credential={access_token}/20260101/us-east-1/s3/aws4_request, "
        "SignedHeaders=host, Signature=stubbed-client-signature"
    )


@pytest.mark.asyncio
async def test_bound_token_with_valid_proof_is_accepted_on_tes_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A DPoP-bound token with a valid proof is accepted, and the token reaches the endpoint's
    own authorization checks.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 200, res.text
    # the endpoint could only authorize the request if it received the token, which it can only
    # read from a `Bearer` Authorization header
    assert any(
        access_token in call.kwargs["body"]
        for call in mock_arborist_request.call_args_list
    )


@pytest.mark.asyncio
async def test_bound_token_with_valid_proof_is_accepted_on_s3_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    An AWS-signed S3 request is accepted when the proof is bound to the token in its
    `Credential` field, and its Authorization header is left untouched.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.get(
        S3_PATH,
        params={"list-type": "2"},
        headers={
            "Authorization": aws_auth_header(access_token),
            # the reverse proxy strips "/workflows" before the request reaches this service
            "DPoP": create_proof(
                dpop_key, "GET", S3_PATH, access_token, external_prefix="/workflows"
            ),
        },
    )
    assert res.status_code == 200, res.text
    assert res.text == MOCKED_S3_RESPONSE_XML


@pytest.mark.asyncio
async def test_bound_token_without_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A DPoP-bound token presented without a proof is rejected, so that stealing the token is
    not enough to use it.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
async def test_unbound_token_without_proof_is_accepted(
    client, access_token_patcher, token_signing_key
):
    """
    A token that is not DPoP-bound still works without a proof: this is how worker pods, which
    authenticate through the `client_credentials` flow, reach these endpoints.
    """
    access_token = create_access_token(token_signing_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
async def test_proof_without_nonce_is_challenged(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof with no nonce is answered with a fresh nonce and a challenge the client retries on.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                signed_overrides={"nonce": None},
            ),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "use_dpop_nonce"
    assert res.headers["DPoP-Nonce"]
    assert 'error="use_dpop_nonce"' in res.headers["WWW-Authenticate"]


@pytest.mark.asyncio
async def test_proof_signed_with_a_nonce_from_another_cluster_is_challenged(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A nonce signed with a different shared secret is not accepted.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                signed_overrides={
                    "nonce": generate_stateless_nonce(
                        secret="some-other-cluster-secret"  # pragma: allowlist secret
                    )
                },
            ),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "use_dpop_nonce"
    assert res.headers["DPoP-Nonce"]


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "signed_overrides",
    [
        pytest.param({"method": "GET"}, id="method-signed-does-not-match"),
        pytest.param(
            {"url": f"{config['DPOP_EXTERNAL_BASE_URL']}/ga4gh/tes/v1/tasks/other"},
            id="url-signed-does-not-match",
        ),
        pytest.param(
            {"url": "https://another-commons.net/ga4gh/tes/v1/tasks"},
            id="url-signed-is-another-commons",
        ),
        pytest.param(
            {"access_token": "an.other.token"}, id="token-hash-does-not-match"
        ),
    ],
)
async def test_proof_that_does_not_match_the_request_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key, signed_overrides
):
    """
    A proof is only accepted for the exact request it was signed for.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                signed_overrides=signed_overrides,
            ),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_proof_signed_with_the_wrong_key_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof signed with a key the token is not bound to is rejected, which is the check that
    makes a stolen token unusable.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    stolen_token_key = jwk.generate_key("EC", "P-256", private=True)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(stolen_token_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_expired_token_with_a_valid_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A valid proof does not make an expired access token usable.
    """
    access_token = create_access_token(
        token_signing_key, dpop_key, exp=int(time.time()) - 1
    )
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_token"


@pytest.mark.asyncio
async def test_token_from_an_unknown_issuer_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A token from an issuer that is not allow-listed is rejected.
    """
    access_token = create_access_token(
        token_signing_key, dpop_key, iss="http://an-untrusted-issuer/user"
    )
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_token"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "headers",
    [
        pytest.param({}, id="no-credentials"),
        pytest.param({"Authorization": "Bearer unbound-token"}, id="unbound-token"),
    ],
)
async def test_proof_is_required_from_everyone_when_dpop_is_required(
    client, access_token_patcher, reset_config_dpop_required, headers
):
    """
    When DPoP is required, a request without a proof is rejected even if it presents no token,
    or a token that is not DPoP-bound.
    """
    config["DPOP_REQUIRED"] = True
    res = await client.post(TES_PATH, json={"name": "test-task"}, headers=headers)
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
async def test_valid_proof_is_still_accepted_when_dpop_is_required(
    client,
    access_token_patcher,
    token_signing_key,
    dpop_key,
    reset_config_dpop_required,
):
    """
    Requiring DPoP does not get in the way of a request that does present a valid proof.
    """
    config["DPOP_REQUIRED"] = True
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
async def test_unprotected_endpoint_is_reachable_when_dpop_is_required(
    client, reset_config_dpop_required
):
    """
    Requiring DPoP must not lock out the status endpoint, which Kubernetes probes call without
    any credentials.
    """
    config["DPOP_REQUIRED"] = True
    res = await client.get("/_status")
    assert res.status_code == 200


@pytest.mark.asyncio
async def test_proof_with_an_unbound_token_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof presented with a token that is not DPoP-bound is rejected: there is no binding to
    prove possession of.
    """
    access_token = create_access_token(token_signing_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_allowed_issuers_default_to_the_configured_hostname(
    client, access_token_patcher, token_signing_key, dpop_key, reset_config_dpop_issuers
):
    """
    With no issuer allowlist configured, a token from the auth service of the configured
    hostname is accepted.
    """
    config["DPOP_ALLOWED_ISSUERS"] = []
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 200, res.text


@pytest.fixture(scope="function")
def reset_config_dpop_issuers():
    """
    Reset the `DPOP_ALLOWED_ISSUERS` configuration at the end of tests that use this fixture.
    """
    original_val = config["DPOP_ALLOWED_ISSUERS"]
    yield
    config["DPOP_ALLOWED_ISSUERS"] = original_val


@pytest.fixture(scope="function")
def reset_config_dpop_required():
    """
    Reset the `DPOP_REQUIRED` configuration at the end of tests that use this fixture.
    """
    original_val = config["DPOP_REQUIRED"]
    yield
    config["DPOP_REQUIRED"] = original_val


@pytest.mark.asyncio
async def test_unprotected_endpoint_does_not_require_a_proof(client):
    """
    Endpoints that are not DPoP-protected are left alone.
    """
    res = await client.get("/_status")
    assert res.status_code == 200


@pytest.mark.asyncio
async def test_bound_token_without_proof_is_accepted_when_dpop_is_disabled(
    client, access_token_patcher, token_signing_key, dpop_key, reset_config_dpop_enabled
):
    """
    Disabling DPoP stops the proof from being required, even for a DPoP-bound token.
    """
    config["DPOP_ENABLED"] = False
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 200, res.text


@pytest.fixture(scope="function")
def reset_config_dpop_enabled():
    """
    Reset the `DPOP_ENABLED` configuration at the end of tests that use this fixture.
    """
    original_val = config["DPOP_ENABLED"]
    yield
    config["DPOP_ENABLED"] = original_val


class TestLocalTestStubs:
    """
    Tests for the temporary canned endpoint responses. Delete alongside
    `DPOP_LOCAL_TEST_STUBS`.
    """

    @pytest.fixture(autouse=True)
    def enable_stubs(self):
        """
        Enable the canned responses, which the test suite disables by default.
        """
        with patch.object(ga4gh_tes, "DPOP_LOCAL_TEST_STUBS", True), patch.object(
            s3, "DPOP_LOCAL_TEST_STUBS", True
        ):
            yield

    @pytest.mark.asyncio
    async def test_stubbed_tes_endpoint_skips_the_tes_server(
        self, client, access_token_patcher, token_signing_key, dpop_key
    ):
        """
        A stubbed task creation returns a task ID without calling the TES server.
        """
        access_token = create_access_token(token_signing_key, dpop_key)
        res = await client.post(
            TES_PATH,
            json={"name": "test-task"},
            headers={
                "Authorization": f"DPoP {access_token}",
                "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
            },
        )
        assert res.status_code == 200, res.text
        assert res.json()["id"]
        mock_tes_server_request.assert_not_called()

    @pytest.mark.asyncio
    async def test_stubbed_s3_endpoint_skips_s3(
        self, client, access_token_patcher, token_signing_key, dpop_key
    ):
        """
        A stubbed bucket listing returns S3-shaped XML without calling S3.
        """
        access_token = create_access_token(token_signing_key, dpop_key)
        res = await client.get(
            S3_PATH,
            params={"list-type": "2"},
            headers={
                "Authorization": aws_auth_header(access_token),
                "DPoP": create_proof(
                    dpop_key, "GET", S3_PATH, access_token, external_prefix="/workflows"
                ),
            },
        )
        assert res.status_code == 200, res.text
        assert f"<Name>{S3_BUCKET}</Name>" in res.text
