"""
Tests for the DPoP (RFC 9449) validation applied to the DPoP-protected endpoints.

The DPoP proofs and nonces here are the real thing, generated with the same `authutils`
functions the clients use. Only the lookup of the access token's signing key is mocked, so
that the tests do not need a live token issuer.
"""

import time
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from authutils.dpop import DPOP_PROOF_MAX_TTL, generate_dpop_proof
from authutils.token.dpop_nonce import generate_stateless_nonce
from fastapi import HTTPException
from joserfc import jwk, jwt

from gen3workflow.config import config, get_dpop_allowed_issuers
from gen3workflow.routes.s3 import set_access_token_and_get_user_id
from tests.conftest import (
    MOCKED_S3_RESPONSE_XML,
    TEST_USER_ID,
    mock_arborist_request,
)

TES_PATH = "/ga4gh/tes/v1/tasks"
TEST_CLIENT_ID = "test-client-id"
S3_BUCKET = f"gen3wf-{config['HOSTNAME']}-{TEST_USER_ID}"
# The S3 endpoint answers on both of these. Every S3 case below runs against both, because the
# root mount matches no `DPOP_PROTECTED_PATHS` prefix and so takes a different route through
# the middleware than the `/s3` one.
S3_PATHS = [
    pytest.param(f"/s3/{S3_BUCKET}", id="s3-prefix"),
    pytest.param(f"/{S3_BUCKET}", id="root-mount"),
]

# Authorization header formats the S3 endpoint accepts that do not start with one of the
# canonical AWS scheme prefixes. It reads the token out of a `Credential=` field or out of an
# `AWS ` segment anywhere in the header, and never checks the request signature, so each of
# these carries a usable credential and has to be held to the same DPoP requirement as a
# canonical one. A horizontal tab is a legal HTTP field value character, so the first needs no
# protocol abuse.
NON_CANONICAL_S3_AUTH_HEADERS = [
    pytest.param(
        "AWS4-HMAC-SHA256\tCredential={token}/20260101/us-east-1/s3/aws4_request, "
        "SignedHeaders=host, Signature=stubbed-client-signature",
        id="tab-after-scheme",
    ),
    pytest.param(
        "Foo Credential={token}/20260101/us-east-1/s3/aws4_request, "
        "SignedHeaders=host, Signature=stubbed-client-signature",
        id="unknown-scheme",
    ),
    pytest.param(
        "Credential={token}/20260101/us-east-1/s3/aws4_request, "
        "SignedHeaders=host, Signature=stubbed-client-signature",
        id="no-scheme",
    ),
    pytest.param("xAWS {token}:stubbed-client-signature", id="scheme-behind-a-prefix"),
]


@pytest.fixture(scope="module")
def token_signing_key():
    """
    The key the token issuer signs access tokens with.
    """
    return jwk.generate_key("RSA", 2048, private=True)


@pytest.fixture(scope="module")
def dpop_key():
    """
    The key a client proves possession of, equivalent to the one generated by the Gen3 SDK.
    """
    return jwk.generate_key("EC", "P-256", private=True)


@pytest.fixture(autouse=True)
def dpop_required():
    """
    Require DPoP for every test in this module, which the shared test configuration does not.
    """
    original_val = config["DPOP_REQUIRED"]
    config["DPOP_REQUIRED"] = True
    yield
    config["DPOP_REQUIRED"] = original_val


@pytest.fixture(autouse=True)
def no_eks_cluster():
    """
    Keep task creation away from AWS: these tests are only about the DPoP flow.
    """
    original_val = config["EKS_CLUSTER_NAME"]
    config["EKS_CLUSTER_NAME"] = ""
    yield
    config["EKS_CLUSTER_NAME"] = original_val


@pytest.fixture(autouse=True)
def mock_token_signing_key_lookup(token_signing_key):
    """
    Return the test signing key instead of fetching the issuer's public keys.
    """
    with patch(
        "authutils.dpop.get_any_public_key_for_token_async",
        new_callable=AsyncMock,
        return_value=token_signing_key.as_pem(private=False),
    ) as mocked_lookup:
        yield mocked_lookup


def create_access_token(token_signing_key, dpop_key=None, **claim_overrides):
    """
    Create an access token as the auth service (e.g. Fence) would issue it.

    Args:
        token_signing_key (jwk.Key): the issuer's signing key
        dpop_key (jwk.Key | None): if provided, the token is bound to this key
        **claim_overrides: claims to add to or replace in the token. A `None` value drops the
            claim, which is how a token with no `sub` (`client_credentials` flow) is built.

    Returns:
        str: the encoded access token
    """
    now = int(time.time())
    claims = {
        "sub": TEST_USER_ID,
        "iss": get_dpop_allowed_issuers()[0],
        "aud": config["VALID_AUTHZ_AUDIENCE"][0],
        "iat": now,
        "exp": now + 300,
        "pur": "access",
        "scope": ["openid", "user"],
    }
    if dpop_key:
        claims["cnf"] = {"jkt": dpop_key.thumbprint()}
    claims.update(claim_overrides)
    claims = {key: value for key, value in claims.items() if value is not None}
    return jwt.encode({"alg": "RS256", "typ": "JWT"}, claims, token_signing_key)


def create_client_credentials_token(token_signing_key, dpop_key=None):
    """
    Create an access token as the auth service would issue it to a client, with no user linked
    to it. This is what the Funnel worker pods authenticate with.

    Args:
        token_signing_key (jwk.Key): the issuer's signing key
        dpop_key (jwk.Key | None): if provided, the token is bound to this key

    Returns:
        str: the encoded access token
    """
    return create_access_token(
        token_signing_key, dpop_key, sub=None, azp=TEST_CLIENT_ID
    )


def create_task_token(token_signing_key, dpop_key=None, task_token_type="WORKFLOW"):
    """
    Create a task token as the auth service would issue it in exchange for an API key: a
    long-lived access token marked with its `context.task_token_type`.

    Args:
        token_signing_key (jwk.Key): the issuer's signing key
        dpop_key (jwk.Key | None): if provided, the token is bound to this key
        task_token_type (str): the type of task token

    Returns:
        str: the encoded task token
    """
    return create_access_token(
        token_signing_key,
        dpop_key,
        context={
            "user": {"name": f"test-username-{TEST_USER_ID}"},
            "task_token_type": task_token_type,
        },
    )


def create_proof(
    dpop_key, method, path, access_token, external_prefix="", signed_overrides=None
):
    """
    Create a DPoP proof for a request, as the client's DPoP proxy would.

    Args:
        dpop_key (jwk.Key): the key to sign the proof with
        method (str): HTTP method of the request the proof is for
        path (str): path of the request, as this service sees it
        access_token (str): the access token the proof is presented with
        external_prefix (str): path prefix the reverse proxy would have stripped
        signed_overrides (dict | None): `method`, `url`, `access_token` or `nonce` values to
            sign instead of the ones matching the request

    Returns:
        str: the encoded DPoP proof
    """
    signed = {
        "method": method,
        "url": f"{config['DPOP_EXTERNAL_BASE_URL']}{external_prefix}{path}",
        "access_token": access_token,
        "nonce": generate_stateless_nonce(secret=config["DPOP_SHARED_SECRET"]),
    }
    signed.update(signed_overrides or {})
    return generate_dpop_proof(key=dpop_key, **signed)


def aws_auth_header(access_token):
    """
    Build the Authorization header an AWS client produces, with the token as the key ID.

    Args:
        access_token (str): the access token

    Returns:
        str: an AWS Signature Version 4 Authorization header value
    """
    return (
        f"AWS4-HMAC-SHA256 Credential={access_token}/20260101/us-east-1/s3/aws4_request, "
        "SignedHeaders=host, Signature=stubbed-client-signature"
    )


@pytest.mark.asyncio
async def test_bound_token_with_valid_proof_is_accepted_on_tes_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A DPoP-bound token with a valid proof is accepted, and the token reaches the endpoint's
    own authorization checks.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 200, res.text
    # the endpoint could only authorize the request if it received the token, which it can only
    # read from a `Bearer` Authorization header
    assert any(
        access_token in call.kwargs["body"]
        for call in mock_arborist_request.call_args_list
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_bound_token_with_valid_proof_is_accepted_on_s3_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key, s3_path
):
    """
    An AWS-signed S3 request is accepted when the proof is bound to the token in its
    `Credential` field, and its Authorization header is left untouched.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={
            "Authorization": aws_auth_header(access_token),
            # the reverse proxy strips "/workflows" before the request reaches this service
            "DPoP": create_proof(
                dpop_key, "GET", s3_path, access_token, external_prefix="/workflows"
            ),
        },
    )
    assert res.status_code == 200, res.text
    assert res.text == MOCKED_S3_RESPONSE_XML


@pytest.mark.asyncio
async def test_bound_task_token_with_valid_proof_is_accepted_on_tes_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """A DPoP-bound task token with a valid proof is accepted on the TES endpoint."""
    access_token = create_task_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_bound_task_token_with_valid_proof_is_accepted_on_s3_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key, s3_path
):
    """A DPoP-bound task token with a valid proof is accepted on the S3 endpoint."""
    access_token = create_task_token(token_signing_key, dpop_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={
            "Authorization": aws_auth_header(access_token),
            "DPoP": create_proof(
                dpop_key, "GET", s3_path, access_token, external_prefix="/workflows"
            ),
        },
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "external_prefix",
    [
        pytest.param("", id="served-as-is"),
        pytest.param("/workflows", id="served-under-workflows"),
    ],
)
async def test_bound_token_with_valid_proof_is_accepted_on_tes_endpoint_under_every_external_prefix(
    client, access_token_patcher, token_signing_key, dpop_key, external_prefix
):
    """
    The reverse proxy serves the TES endpoints both as-is and under "/workflows", so a proof
    signed for either URL is accepted.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                external_prefix=external_prefix,
            ),
        },
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "object_key",
    [
        pytest.param("my%20file.txt", id="space"),
        pytest.param("caf%C3%A9.txt", id="non-ascii"),
        pytest.param("folder%2Ffile.txt", id="encoded-slash"),
    ],
)
async def test_bound_token_with_valid_proof_is_accepted_for_percent_encoded_s3_object_key(
    client, access_token_patcher, token_signing_key, dpop_key, object_key
):
    """
    A proof signed for the percent-encoded URL an S3 client sends is accepted for that request.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    s3_path = f"/s3/{S3_BUCKET}/{object_key}"
    res = await client.get(
        s3_path,
        headers={
            "Authorization": aws_auth_header(access_token),
            "DPoP": create_proof(
                dpop_key, "GET", s3_path, access_token, external_prefix="/workflows"
            ),
        },
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_bound_token_without_proof_is_rejected_on_s3_endpoint(
    client, access_token_patcher, token_signing_key, dpop_key, s3_path
):
    """
    A DPoP-bound token presented to the S3 endpoint without a proof is rejected, on the root
    mount as well as under `/s3`.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={"Authorization": aws_auth_header(access_token)},
    )
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_unbound_task_token_without_proof_is_rejected_on_s3_endpoint(
    client, access_token_patcher, token_signing_key, s3_path
):
    """
    A task token that is not DPoP-bound is rejected on the S3 endpoint, on the root mount as
    well as under `/s3`.
    """
    access_token = create_task_token(token_signing_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={"Authorization": aws_auth_header(access_token)},
    )
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_unbound_regular_token_without_proof_is_accepted_on_s3_endpoint(
    client, access_token_patcher, token_signing_key, s3_path
):
    """
    A regular access token, neither DPoP-bound nor a task token, is accepted on the S3 endpoint
    without a proof.
    """
    access_token = create_access_token(token_signing_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={"Authorization": aws_auth_header(access_token)},
    )
    assert res.status_code == 200, res.text
    assert res.text == MOCKED_S3_RESPONSE_XML


@pytest.mark.asyncio
@pytest.mark.parametrize("auth_header_format", NON_CANONICAL_S3_AUTH_HEADERS)
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_bound_token_without_proof_is_rejected_on_s3_endpoint_whatever_the_auth_header_format(
    client,
    access_token_patcher,
    token_signing_key,
    dpop_key,
    s3_path,
    auth_header_format,
):
    """
    A DPoP-bound token is rejected without a proof however its Authorization header is
    formatted. The root mount matches no `DPOP_PROTECTED_PATHS` prefix, so the header is the
    only thing identifying an S3 request there: a format the middleware fails to recognize
    would otherwise let a stolen bound token through as an ordinary bearer credential.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={"Authorization": auth_header_format.format(token=access_token)},
    )
    assert res.status_code == 401, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize("auth_header_format", NON_CANONICAL_S3_AUTH_HEADERS)
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_unbound_task_token_without_proof_is_rejected_on_s3_endpoint_whatever_the_auth_header_format(
    client,
    access_token_patcher,
    token_signing_key,
    s3_path,
    auth_header_format,
):
    """
    A task token that is not DPoP-bound is rejected however its Authorization header is
    formatted.
    """
    access_token = create_task_token(token_signing_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={"Authorization": auth_header_format.format(token=access_token)},
    )
    assert res.status_code == 401, res.text
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
async def test_bound_token_without_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A DPoP-bound token presented without a proof is rejected, so that stealing the token is
    not enough to use it.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
async def test_proof_without_nonce_is_challenged(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof with no nonce is answered with a fresh nonce and a challenge the client retries on.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                signed_overrides={"nonce": None},
            ),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "use_dpop_nonce"
    assert res.headers["DPoP-Nonce"]
    assert 'error="use_dpop_nonce"' in res.headers["WWW-Authenticate"]


@pytest.mark.asyncio
async def test_proof_signed_with_a_nonce_from_another_cluster_is_challenged(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A nonce signed with a different shared secret is not accepted.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                signed_overrides={
                    "nonce": generate_stateless_nonce(
                        secret="some-other-cluster-secret"  # pragma: allowlist secret
                    )
                },
            ),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "use_dpop_nonce"
    assert res.headers["DPoP-Nonce"]


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "signed_overrides",
    [
        pytest.param({"method": "GET"}, id="method-signed-does-not-match"),
        pytest.param(
            {"url": f"{config['DPOP_EXTERNAL_BASE_URL']}/ga4gh/tes/v1/tasks/other"},
            id="url-signed-does-not-match",
        ),
        pytest.param(
            {"url": "https://another-commons.net/ga4gh/tes/v1/tasks"},
            id="url-signed-is-another-commons",
        ),
        pytest.param(
            {"url": f"{config['DPOP_EXTERNAL_BASE_URL']}/other/ga4gh/tes/v1/tasks"},
            id="url-signed-under-an-unconfigured-prefix",
        ),
        pytest.param(
            {"url": f"{config['DPOP_EXTERNAL_BASE_URL']}/ga4gh/tes/v1/tasks%2Fother"},
            id="url-signed-decodes-to-another-path",
        ),
        pytest.param(
            {"access_token": "an.other.token"}, id="token-hash-does-not-match"
        ),
    ],
)
async def test_proof_that_does_not_match_the_request_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key, signed_overrides
):
    """
    A proof is only accepted for the exact request it was signed for.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(
                dpop_key,
                "POST",
                TES_PATH,
                access_token,
                signed_overrides=signed_overrides,
            ),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_a_second_request_with_a_fresh_proof_is_accepted(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    Single-use applies to the proof, not to the token: the same token keeps working as long
    as each request carries its own proof.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    for _ in range(2):
        res = await client.post(
            TES_PATH,
            json={"name": "test-task"},
            headers={
                "Authorization": f"DPoP {access_token}",
                "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
            },
        )
        assert res.status_code == 200, res.text


@pytest.mark.asyncio
async def test_stale_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof is refused once it is older than `DPOP_PROOF_MAX_TTL`. With no `jti` tracking
    here, that age is what bounds how long a captured proof can be replayed, so it is worth
    asserting at this layer and not only in authutils.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    stale_iat = int(time.time()) - DPOP_PROOF_MAX_TTL - 10
    with patch("authutils.dpop.time.time", return_value=stale_iat):
        stale_proof = create_proof(dpop_key, "POST", TES_PATH, access_token)

    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"DPoP {access_token}", "DPoP": stale_proof},
    )
    assert res.status_code == 401, res.text
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_rejection_does_not_echo_the_expected_request_url(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A rejection says what went wrong without quoting the URL this service expected. That URL
    describes the reverse proxy's path mapping, which a caller has no need for.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    proof = create_proof(
        dpop_key,
        "POST",
        TES_PATH,
        access_token,
        signed_overrides={
            "url": "https://somewhere-else.example.org/ga4gh/tes/v1/tasks"
        },
    )
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"DPoP {access_token}", "DPoP": proof},
    )
    assert res.status_code == 401
    assert config["DPOP_EXTERNAL_BASE_URL"] not in res.text


@pytest.mark.asyncio
async def test_proof_signed_with_the_wrong_key_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof signed with a key the token is not bound to is rejected, which is the check that
    makes a stolen token unusable.
    """
    access_token = create_access_token(token_signing_key, dpop_key)
    stolen_token_key = jwk.generate_key("EC", "P-256", private=True)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(stolen_token_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_expired_token_with_a_valid_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A valid proof does not make an expired access token usable.
    """
    access_token = create_access_token(
        token_signing_key, dpop_key, exp=int(time.time()) - 1
    )
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_token"


@pytest.mark.asyncio
async def test_token_from_an_unknown_issuer_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A token from an issuer that is not allow-listed is rejected.
    """
    access_token = create_access_token(
        token_signing_key, dpop_key, iss="http://an-untrusted-issuer/user"
    )
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_token"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "task_token_type",
    [pytest.param("WORKFLOW", id="workflow"), pytest.param("", id="empty")],
)
async def test_unbound_task_token_without_proof_is_rejected(
    client, access_token_patcher, token_signing_key, task_token_type
):
    """
    A task token that is not DPoP-bound is rejected whatever its type, so that a long-lived
    token cannot be used as an ordinary bearer credential.
    """
    access_token = create_task_token(token_signing_key, task_token_type=task_token_type)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
async def test_unbound_task_token_with_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A task token that is not DPoP-bound cannot get through by presenting a proof: there is no
    binding to prove possession of.
    """
    access_token = create_task_token(token_signing_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "token_factory",
    [
        pytest.param(create_access_token, id="user-token"),
        pytest.param(create_client_credentials_token, id="client-credentials-token"),
    ],
)
async def test_unbound_regular_token_without_proof_is_accepted(
    client, access_token_patcher, token_signing_key, token_factory
):
    """
    A regular access token, neither DPoP-bound nor a task token, is accepted without a proof
    and left to the endpoint's own validation.
    """
    access_token = token_factory(token_signing_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
async def test_anonymous_service_info_request_is_accepted(client, trailing_slash):
    """A request with no credentials at all reaches `GET /service-info`, which is public."""
    res = await client.get(f"/ga4gh/tes/v1/service-info{'/' if trailing_slash else ''}")
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize("client", [pytest.param({"authorized": True})], indirect=True)
@pytest.mark.parametrize(
    "method,path,body",
    [
        pytest.param("POST", TES_PATH, {"name": "test-task"}, id="create-task"),
        pytest.param("GET", TES_PATH, None, id="list-tasks"),
        pytest.param("GET", f"{TES_PATH}/123", None, id="get-task"),
        pytest.param("POST", f"{TES_PATH}/123:cancel", None, id="cancel-task"),
        pytest.param(
            "POST", "/ga4gh/tes/v1/service-info", None, id="service-info-wrong-method"
        ),
        pytest.param("GET", "/s3/bucket/key", None, id="s3"),
    ],
)
async def test_anonymous_request_to_a_non_public_endpoint_is_rejected(
    client, method, path, body
):
    """
    A request with no credentials at all is rejected on every protected endpoint that is not
    public, even when Arborist would allow it.
    """
    res = await client.request(method, path, json=body)
    assert res.status_code == 401, res.text
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "access_token_patcher",
    [{"user_id": None, "client_id": TEST_CLIENT_ID}],
    indirect=True,
)
@pytest.mark.parametrize("s3_path", S3_PATHS)
async def test_client_token_on_behalf_of_a_user_is_rejected_on_s3_endpoint(
    client,
    access_token_patcher,
    token_signing_key,
    s3_path,
):
    """
    A client token presented as the AWS access key ID with the ID of the user it acts on behalf
    of appended to it is rejected.
    """
    access_token = create_client_credentials_token(token_signing_key)
    res = await client.get(
        s3_path,
        params={"list-type": "2"},
        headers={
            "Authorization": aws_auth_header(f"{access_token};userId={TEST_USER_ID}")
        },
    )
    assert res.status_code == 401, res.text


@pytest.mark.asyncio
async def test_bound_client_credentials_token_without_proof_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A token that is DPoP-bound always requires a proof, even when it is a client's.
    """
    access_token = create_client_credentials_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 401
    assert res.json()["error"] == "dpop_required"


@pytest.mark.asyncio
async def test_unprotected_endpoint_is_reachable(client):
    """
    Requiring DPoP must not lock out the status endpoint, which Kubernetes probes call without
    any credentials.
    """
    res = await client.get("/_status")
    assert res.status_code == 200


@pytest.mark.asyncio
async def test_proof_with_an_unbound_token_is_rejected(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    A proof presented with a token that is not DPoP-bound is rejected: there is no binding to
    prove possession of.
    """
    access_token = create_access_token(token_signing_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 401
    assert res.json()["error"] == "invalid_dpop_proof"


@pytest.mark.asyncio
async def test_allowed_issuers_default_to_the_configured_hostname(
    client, access_token_patcher, token_signing_key, dpop_key, reset_config_dpop_issuers
):
    """
    With no issuer allowlist configured, a token from the auth service of the configured
    hostname is accepted.
    """
    config["DPOP_ALLOWED_ISSUERS"] = []
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={
            "Authorization": f"DPoP {access_token}",
            "DPoP": create_proof(dpop_key, "POST", TES_PATH, access_token),
        },
    )
    assert res.status_code == 200, res.text


@pytest.fixture(scope="function")
def reset_config_dpop_issuers():
    """
    Reset the `DPOP_ALLOWED_ISSUERS` configuration at the end of tests that use this fixture.
    """
    original_val = config["DPOP_ALLOWED_ISSUERS"]
    yield
    config["DPOP_ALLOWED_ISSUERS"] = original_val


@pytest.mark.asyncio
async def test_bound_token_without_proof_is_accepted_when_dpop_is_not_required(
    client, access_token_patcher, token_signing_key, dpop_key
):
    """
    Turning `DPOP_REQUIRED` off stops the proof from being required, even for a DPoP-bound
    token.
    """
    config["DPOP_REQUIRED"] = False
    access_token = create_access_token(token_signing_key, dpop_key)
    res = await client.post(
        TES_PATH,
        json={"name": "test-task"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    assert res.status_code == 200, res.text


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "claims",
    [
        pytest.param({"cnf": {"jkt": "some-thumbprint"}}, id="bound-token"),
        pytest.param({"context": {"task_token_type": "WORKFLOW"}}, id="task-token"),
    ],
)
async def test_s3_endpoint_rejects_token_requiring_a_proof_without_a_validated_one(
    claims,
):
    """
    The S3 endpoint itself refuses a token that requires a proof when the middleware did not
    validate one, in case a request reaches it without going through the middleware's checks.
    """
    auth = MagicMock()
    auth.get_token_claims = AsyncMock(return_value={"sub": TEST_USER_ID, **claims})
    with pytest.raises(HTTPException) as e:
        await set_access_token_and_get_user_id(
            auth,
            {"authorization": aws_auth_header("some-token")},
            dpop_validated=False,
        )
    assert e.value.status_code == 401


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "claims",
    [
        pytest.param({"cnf": {"jkt": "some-thumbprint"}}, id="bound-token"),
        pytest.param({"context": {"task_token_type": "WORKFLOW"}}, id="task-token"),
    ],
)
async def test_s3_endpoint_accepts_token_requiring_a_proof_with_a_validated_one(claims):
    """The S3 endpoint accepts a token that requires a proof once the middleware validated one."""
    auth = MagicMock()
    auth.get_token_claims = AsyncMock(return_value={"sub": TEST_USER_ID, **claims})
    user_id, _ = await set_access_token_and_get_user_id(
        auth,
        {"authorization": aws_auth_header("some-token")},
        dpop_validated=True,
    )
    assert user_id == TEST_USER_ID
